kind: pipeline
type: docker
name: Build Main

trigger:
  event:
    - push
  branch:
    - main

steps:
  - name: restore-cache
    image: drillster/drone-volume-cache
    settings:
      restore: true
      mount:
        - ./node_modules
        - ./.cache
        - ./public
    volumes:
      - name: cache
        path: /cache

  - name: build
    image: node
    commands:
      - yarn install
      - yarn build
      - du -sh public

  - name: rsync
    image: drillster/drone-rsync
    settings:
      user: ci
      key:
        from_secret: rsync_key
      hosts:
        - droplet.chuckdries.com
      exclude:
        - node_modules
        - .git*
      source: ./public/
      target: ~/www/personal-website
      delete: true
      recursive: true
      secrets: [rsync_key]

  - name: rebuild-cache
    image: drillster/drone-volume-cache
    settings:
      rebuild: true
      mount:
        - ./node_modules
        - ./.cache
        - ./public
    volumes:
      - name: cache
        path: /cache

volumes:
  - name: cache
    host:
      path: /mnt/user/dronecache

---
kind: pipeline
type: docker
name: Preview PR

trigger:
  event:
    - pull_request

steps:
  - name: restore-cache
    image: drillster/drone-volume-cache
    settings:
      restore: true
      mount:
        - ./node_modules
        - ./.cache
        - ./public
    volumes:
      - name: cache
        path: /cache

  - name: build
    image: node
    commands:
      - yarn install
      - PATH_PREFIX=/${DRONE_PULL_REQUEST} yarn build --prefix-paths
      - du -sh public

  - name: rsync
    image: drillster/drone-rsync
    settings:
      user: ci
      key:
        from_secret: rsync_key
      hosts:
        - droplet.chuckdries.com
      exclude:
        - node_modules
        - .git*
      source: ./public/
      target: ~/www/personal-website-preview/${DRONE_PULL_REQUEST}
      prescript: cp -r ~/www/personal-website ~/www/personal-website-preview/${DRONE_PULL_REQUEST}
      delete: true
      recursive: true
      secrets: [rsync_key]

  - name: comment
    image: jmccann/drone-github-comment:1
    settings:
      message: preview of ${DRONE_COMMIT} deployed to https://preview.chuckdries.com/${DRONE_PULL_REQUEST}
      update: true
      api_key:
        from_secret: github_key
# note: we intentionally do not rebuild-cache for PRs

---
kind: secret
name: github_key
data: xlAGWGo9tPsl21AS9jDuFbXd6d7QjHLA26KD9gHXjth5FYyAOE51VBPNAmnW1gM9nCBD7AjUJqqCwHi1QwkmPw4NPH8

---
kind: secret
name: rsync_key
data: 31O7VrzZWYwXpixiCsrk1vU3a2/ksgwveBe1T0lSGkeN5jvELBz3ZJQg+0X6VyL/Rr3G7pLjITJJAY8BRFH5OhN9bBpvxiuhZk5VVhLSl3kmWv++5V7fsJvSuvHtozxnMgw3Bre9PUSQMUb6xPUk7n7SC36W1BsrZdIM4SL9cy612jcq/qm46ljtM3wezTCYedy9m5LUl+JevBVt5mQ9sOkgSTwfqGtMFyVSTMR0D5RWiXMNleEK3cMAiwQwRYZ4w0Eqzkv9X49IpyDzUDnHFbaeI1wcyJIHOUfzzai/nk+40xPbtYvZLrOq+liw9l1JIw2Bjt2dKx1T60dhmcogXB1TZcsp9FOLDXz4CQFAxuHL7Cu1agdCBixSnUCgnZDmLbpL39TKmZEx721PCA2wY8LdBKQ9/fBHcuxZJcdjkEa4KDfE00aBP0FmDWBlYT2/l1FjNHDabxgGWTtO68VM5+cYnQ3rrBMTMVCsCMi00O412R3kHX9bFp0WRN9J09hpjp9CM1XJ545dHWLSbGhHt0xrh136KuJ779iddsFZM5oBQIw/YZkdj+5PBXxMcCCNahkbwThi+OBrP6CI6EVS7/ZvHm9Rty3FxI3KfLu2MXslpwwbaO6lrRHz24NmHFh/LoVjTDlBeCqQbvpbI8Fpdoa9/rh5qigDCUq9Iz7/XcOMkIfSE1R+Mfp7+Wfk58cJNK8GD7bn9e8IEHN8N6Sc+akAW+MwdEd+bGdZmPo7AUtZzrnQE1rKK7VQZv6+Zllqqx7WQXG7aQfC4mUZraR/MJ0wCDjiWI7MaiaVFbSSmYBGTqmUQ7aWYnNb2wY0Fe/I9zXMwDgfgYPIDvL2s4dep2kK5YiitkT/woae5rhMhIZIHjs7kVQdZpofXyWyN/BdSlEwS1HQJgbmhMn2SkNYfcUo4u0vcywEjH4LOLjZTZfo1CQha3PNPWlm5jyDzizwlpnwrSMPM9uMKps4qodixCByaQmMyvzZjmqSvejc6YlLRN80sbGWwr9dawqFZMch7PLCBEYdQ2HXzPU2kLrgzDv9ZYURgosRc+oWWy++NTbPqqeNBo4HEXb9E400P08mHD9HoSj60PBt6cd076PLD2FNWMLo01guC+KASfcif92D734TshTtg5lAiFkC6WixT8dWd/S+kOWEeLE+HFOQBNctyf8tpVlvxU7uqztGSxKGmU4H0KujmucWTmkw7da2mwEDsqEPlZMZy2ECYkXUzwjlks5HgOY/PNDbP8n3G0XYgHwPqQFov1JiYYNRWrbTbDG4SLA+wWTnba4TkvTns1iU+nksWaWgUy1nfSvPw2BAfKNHGZFzHuWMURo+Tks7vpNHP1ZBlN8UFZU/gtiEXMdwdEppIesdr3SAOpO7PhM1E67D2tHQBKdByOgwY+e/NMmGcmIR9zn4C9mEjC+eREcorD4tUcIGQIuWn0ao3E21FVLc+iXPbX5VusN7WZ7yJaJNRAfBe+Q3DIJ86LNAwbEg9XdkjP6JXwXgDXLwVdPacLimNOvNFctBiXKhK2pV4SSy3XTVKyqtMKQ1BQn79Vsnxd5lXZrRGaAX74jl63b/8qmqwCsyHMRcYc6AzJ0uqioAkxTNHtlykj7Mh6BYcEYu/Cqqm6QLS359xpFktxdKGs3Sc62vW2cMWjN7/D3Gow/6R8HKpRkGHlDV0NXTPmVpQy/w80Glu8L4hfvQ2MpW1/57q79CIoRtMcy9ItP1fbtmC04s3qiSRaR2mj/vYYnAI4pDV4GQhqGBzrmhmOfX/E3ijyKkv5vQj1jC3ZIWBXIxKgQSkilC4SKnXuG2iykvBSosiSm3X6vgohSD1Xa/6/wAfL6R2lMBZnuiRRHR4yFPK8fIt84AY9oOYflgpQ0Hl1FaZxwCKYQ04Z4jpqVazk8+zamk6VOxiQZay33xLH5Bek3g+mY12oqz3lds7ri5BR48u5gWbk5Yvgw8Eewh/+MUdsDBiX2oycYHHlzZgCqzlMFfWr3OBNllGo/v2toTn3v0ZTGbfuIBiLIEaF7516tT+ptx6JnCyESV8an5YRQv8K2H3s6W8S8/QRmCw3qQFK3dJjUqUVJZ8Bf4hCRA82yF+4CYPeGs+GIBYR4rBfTHtU93ZJL+MnmIWj/cH2QB2DtllNLqWpuFES+4wLacACGEI8crbiVtkvTOoSrgzUFLDq3lLRIOvzFMS3YYVMLxddDUEUbYWWyikfiUVzFaydK3artZpAF++r84G078Z9kuvIh3yCLHC6BYbjAMOORmyG+8lR1frwe7WhW7I+sjc6fyjxqOHGRhj+b5uPLhZ0c2/RfS3uHv5E8ZOH9iLgZaqkwmEYaZyyTK//DsHWleeEkPS2tfLdb8wPQeJapAU30fDt5E0C1/oRapDpqir6KTTajN+es2ZkCzQMTxlwCRKFU2Wj5iQS9dSJwrF4WodKdKWgnqs7IlsSx1YWEEIEdxz5sZKH4y3lu+6hnBWbMZjANxrKBCxLws7WrhhePI98dNkFfqYEcMn3psjWGMLx7vdz/1VipuxB12nnU5DLjO0FedVhbSGqxmFf/OCKpp6C5p62ucGLWW1TtSoIhrLT0pTAaTCaTP4v5HMgFXFTZKRbr/b2CqvvTSiHMV9Xu+Z8iRbqvGhyWtVSXUQC8IswiG/y9oqkOU68UNY9behkfKfW0mIfmWLbIOJRrqdIl7UhfxujpOcU/PpW4r8XKJSrlMfJlu4DB/lzprtmAKWlgoq3X2haIBK9/dbT/XqQzdlIPPX0GDlCjKhnfYGazIHul2Xe8uQ0OU/zNPyghwLQiIUStda8WrdVm7dIdyO90VxBO+jAVdPIYUOXOfwwGrQ9Jt/fIXAdyrmUr8T9Spwpb2OoA4UsQ23x/mBfYZyNvmwN1VSiVZNduTye2AVtIZta5sJtndDaAJBA4FlEe1Ok4RujhFF0esboB2HI+9opXJMi7kMjDxJrrcYa/qlj1jIfPPJccTW3peQwb3b00+DFxA4lP+dDq6sYsCwF5/A6kKSfbfZ5vBLrGpEKV9/4Gi/rOlx72mhObqWG5nWPkgDbrrCCDgfWoJ+/WYciQOC1v2zDCRBJ+u0AwVCLAU11g8DhOFQ7Mmkd3S86Bv5gARxlE9hAePVHeleDz/cMAI8+g3xwLoNnlEnZUj/8qhQeiGg7xdf9bXrPMD/xjj2W9hsZQa1E0tgKwMujzeUou2BZhs9biZB6rDI8c0FI43PBck734RgNl1fb3vPTzZvIMXmNh2pG4NUpgEL8DBD7kK4sni8hASiq7ijJLkEFo80Xnoxy8qBdX690AooJNszf++Tms2m4HDvFVnIE/RYqv76XlMp3oqU5XkD1UU5rYohWveF1JJd38GJ6cnPo4wRwBS+lZiL0gLTDxK1jYJt1lNa6dXL6ViKfpjfBIEzRHCxWkNvSlxfXSWap60qNITlZyL2ya4iSFLaw9baFtRQBudJdtBE0DVuMBb0gc1e9uBKZ7srExWSj6bYNckC8WWamOU2CCNo9vUsIvEuFlIe4luMzAqoCELOuoLIFcSoFlM/rlL0XOf63A7PyE=
