kind: pipeline
type: docker
name: default

trigger:
  branch:
    - drone
    - main

steps:
  - name: build
    image: node
    volumes:
      - name: cache
        path: /tmp/cache
    commands:
      - yarn install
      # - yarn build

volumes:
  - name: cache
    host:
      path: /mnt/user/dronecache
