compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

npmScopes:
  juliangarnierorg:
    npmAuthToken: "${GITHUB_NPM_TOKEN}"
    npmRegistryServer: "https://npm.pkg.github.com"

supportedArchitectures:
  cpu:
    - x64
    - arm64
  os:
    - darwin
    - linux
    - win32

yarnPath: .yarn/releases/yarn-4.10.3.cjs
