compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.6.0.cjs

npmScopes:
  juliangarnierorg:
    npmAuthToken: ${GITHUB_NPM_TOKEN}
    npmRegistryServer: "https://npm.pkg.github.com"

supportedArchitectures:
  os:
    - "darwin"
    - "linux"
    - "win32"
  cpu:
    - "x64"
    - "arm64"
