# This is a basic workflow to help you get started with Actions

name: deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  copy-to-server:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Copy folder content recursively to remote
      uses: ThomasRutzer/github-action-scp@master
      with:
        local: "./"
        remote: ${{ secrets.DEPLOY_PATH }}
        host: "server.chuckdries.com"
        username: ${{ secrets.CI_USER }}
        password: ${{ secrets.CI_PASSWORD }}
        rmRemote: true
#     - name: copy file via ssh password
#       uses: appleboy/scp-action@master
#       with:
#         host: "server.chuckdries.com"
#         username: ${{ secrets.CI_USER }}
#         password: ${{ secrets.CI_PASSWORD }}
# #         port: ${{ secrets.PORT }}
#         source: "*/*.*, *.*"
#         target: "/docker-services/letsencrypt/www"
#         rm: true
